# SPDX-FileCopyrightText: 2025 Madeline Baggins <madeline@baggins.family>
#
# SPDX-License-Identifier: GPL-3.0-only

[package]
name = "recipe-server"
version = "0.2.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
